### ISSUE TITLE
Which pins for SCL and SDA?

### ISSUE THREAD

**Issue by gmiller123456** [smartynov/AMG8833-Thermal-Cam#2]
By default, what pins should be used for SDA and SCL?  Every pinout I can find shows it should be 21 and 22.  But in order to get that to work I have to change the Wire.begin() to Wire.begin(21,22) and it works fine after that.

**Comment by smartynov** [comment]
It might seem a little tricky, but I'll try to explain in detail.

1. My code relies on a standard Wire library and does not specify pins explicitly. 
2. The Wire library by default [uses SDA SCL constants](https://github.com/espressif/arduino-esp32/blob/master/libraries/Wire/src/Wire.cpp#L71) which are typically defined somewhere in the configuration of your compiler environment depending on the board configuration.
3. If you used the code with Platformio, my version of `platformio.ini` [specifies the board](https://github.com/smartynov/AMG8833-Thermal-Cam/blob/master/platformio.ini#L13) as `esp32dev`.
4. Configuration of this board [in platformio sources assumes](https://github.com/platformio/platform-espressif32/blob/develop/boards/esp32dev.json#L12) the _variant_ of `esp32` (the default one).
5. Now heading to the Arduino core for the ESP32 sources we can finally see that SDA / SCL [for this board variant are defined as](https://github.com/espressif/arduino-esp32/blob/master/variants/esp32/pins_arduino.h#L17) 21 / 22 respectively.

Therefore, by default it should work as 21 / 22. If adding explicit `Wire.begin(21,22) ` helped you, then probably you had selected another board with different pinout, or maybe you have SDA / SCL constants redefined somewhere.

**Comment by gmiller123456** [comment]
Ah, I used the Arduino IDE, so the INI file didn't come into play.  Thanks.
